### ISSUE TITLE
how to test category variable inside template/category.html?

### ISSUE THREAD

**Issue by horstjens** [horstjens/internationalopenmagazine#6]
twitchy-theme:
i can add html code inside category.html but i am unable to do:

{% if category == 'podcast' %}
some specific podcast text
{% endif %}

**Comment by chbw** [comment]
I've got a POC working: 9abea6836b99ada25116f8e361508a976b374f43

Just make sure to run pelican with the _local copy_ of the theme. If you installed it with `pelican-themes`, then the _installed copy_ would be used instead.

The command I ran was:
`pelican -t mythemes/twitchymagazine/`

**Comment by horstjens** [comment]
i usually install my themes globally using
`pelican-themes -r twitchymagazine`
`pelican-themes -i mythemes/twitchymagazine/`
`pelican content`
maybe i messed up something. i also suspect that my chromium browser has a tendency to show cached sides instead of the new ones, despite clicking shift-reload.

very good idea #7 
it's on my todo list!

**Comment by horstjens** [comment]
tested with local and global themes, and also with firefox and chromium. i can see plain text that i add into categorie.html, but i see nothing inside the if block
    {% if category == 'blog' %}
         here i should see stuff but it remains invisible
   {% endif %}

**Comment by chbw** [comment]
I can reproduce the problem now. When I had it working previously, I had the "stock ubuntu" version of pelican (`sudo apt-get install python-pelican`), not the version from github as descibed in  [localinstall.md](https://github.com/horstjens/internationalopenmagazine/blob/master/localinstall.md).

Working setup:
- Ubuntu 15.04
- python-pelican
- `pelican -t mythemes/twitchymagazine/`

Non-working setup
- Ubuntu 15.04
- `sudo pip install -e "git+https://github.com/getpelican/pelican.git#egg=pelican"`
- local theme `pelican -t mythemes/twitchymagazine/`
- installed theme `sudo pelican-themes -i mythemes/twitchymagazine/`and `pelican`

Looks like something changed in pelican which causes the issue.

**Comment by horstjens** [comment]
Thanks for the hint! if i can manage to get it working with the ubuntu-pelican instead of the github-pelican i see no need for the github-pelican. i was assuming the github version is newer and works better.

**Comment by horstjens** [comment]
i re-installed ubuntu 15.10 , installed python-pelican via synaptic (3.6.3.1) and still have the same problem

**Comment by chbw** [comment]
For the sake of reproducibility I created a branch in my repo which includes a Makefile and a Vagrantfile; the following has been tested with commit 675a8ca492530a9e6ebeabd15a757cd6e8f27f4b.

If you have `vagrant` and `virtualbox` installed then a `vagrant up` will bring up a debian/jessie64 VM. Within the guest VM it will:
- install python-pelican and nginx
- tweak the nginx config to serve pelican output
- remove the old pelican output
- run pelican to create the html files again

The newly generated site will be reachable on the host at http://localhost:8080 and, at least on my notebook, _the site has category-specific text_.

Could you please try this out at your end too?

If you have any questions regarding the vagrant stuff, feel free to ask.

**Comment by horstjens** [comment]
o mighty @chbw , it worked!

i did (on ubuntu-mate 15.10):
- copied both the Vagrantfile and the Makefile 
- sudo apt-get install virtualbox vagrant
- changed into the internationalopenmagazine directory (where the Vagrantfile lies)
- typed `vagrant up` and waited
- started a local server, could see no change
- tried `vagrant reload` nothing happened, had to type ctrl + c
- typed `vagrant destroy`  and then `vagrant up` again
- looked into output/category/blog.html , _i could  see the category-specific text_
- started a local server, i could see the category-specific text in the browser !

But what does this all means? 
Is there a difference between the ubuntu version of pelcian and the debian/jessie64 version of pelican?

do i now have to always do `vagrant up` before uploading the files to the (real) server?

**Comment by chbw** [comment]
I'm glad it works on your end too.

> But what does this all means?

Well, somewhere in your environment, something is different from my setup (which is actually kinda messy) and the reproducible setup with vagrant (debian/jessie64).

Because the issue is related to template processing (expressions work, but control structures don't) I suggest comparing the jinja2-versions first.

Regarding the vagrant setup: `vagrant up` will start a VM and, if necessary, create it. The folder where the `Vagrantfile` resides is available to the VM as `/vagrant` and is exactly the same. If you delete a file in the VM it is gone on the host too. Within the `Vagrantfile`, there is a provisioning part which is run during the first boot of the VM. In our case, it includes a shell script that makes sure all the packages are installed and correctly configured. Specifically, the script modifies `/etc/nginx/sites-enabled/default` to serve up `/vagrant/output` by default. In addition to that, the script will `cd` into `/vagrant` and run `make clean` followed by `make html` to generate the blog.

After the first `vagrant up` you can issue a `vagrant provision` to re-execute the provisioning step. This will regenerate the blog, but not necessarily with the command line you want or like. In addition, it will needlessly go through the `apt-get update` and `apt-get install ...` again. So instead of re-running the provisioning step I recommend to run `vagrant ssh` which will drop you onto the VMs command line. There you can `cd /vagrant` and run pelican in any way you want it to from a known-good environment.

**Comment by horstjens** [comment]
works like a charm. i had to modify the makefile and do `sudo apt-get install rsync` inside vagrant.
now i use vagrant for 
`pelican content`
and
`make rsync_upload`

file editing, starting local server etc. can be done as always, outside vagrant.
